 
-- MySQL Script generated by MySQL Workbench
-- ter 28 abr 2020 23:39:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ControleSementes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ControleSementes` ;

-- -----------------------------------------------------
-- Schema ControleSementes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ControleSementes` DEFAULT CHARACTER SET utf8 ;
USE `ControleSementes` ;

-- -----------------------------------------------------
-- Table `ControleSementes`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleSementes`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `ControleSementes`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleSementes`.`medidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleSementes`.`medidas` ;

CREATE TABLE IF NOT EXISTS `ControleSementes`.`medidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temp` FLOAT NULL,
  `data` DATETIME NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`),
  INDEX `fk_medidas_usuarios_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_medidas_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `ControleSementes`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
